"""Dati di seed.

- 12 scenari con titolo e descrizione.
- Solo lo scenario 1 "Im Supermarkt" ha contenuti completi (key_phrases,
  swiss_variants, imprevisti, goals, ~40 vocaboli curati).
- Gli scenari 2-12 verranno generati dal Planer (task 3.4) e revisionati.

Nota sui campi vocabolo:
- ``de`` include l'articolo (es. "der Einkaufswagen") come nel design.
- ``gender`` è l'articolo "der"/"die"/"das" (o None per verbi/frasi/avverbi).
"""

SCENARIOS = [
    {
        "slug": "im-supermarkt",
        "title_de": "Im Supermarkt",
        "title_it": "Al supermercato",
        "week_number": 1,
        "description": "Fare la spesa al supermercato: chiedere un prodotto, pesare frutta e verdura, pagare alla cassa.",
        "role_label": "Verkäuferin am Supermarkt",
        "key_phrases": [
            {"de": "Ich hätte gern…", "it": "Vorrei…", "example": "Ich hätte gern sechs Eier."},
            {"de": "Hätten Sie…?", "it": "Avrebbe…?", "example": "Hätten Sie noch frische Äpfel?"},
            {"de": "im Angebot", "it": "in offerta", "example": "Die Äpfel sind diese Woche im Angebot."},
            {"de": "Brauchen Sie eine Tüte?", "it": "Le serve un sacchetto?", "example": "Brauchen Sie noch eine Tüte?"},
            {"de": "Zahlen Sie bar oder mit Karte?", "it": "Paga in contanti o con carta?", "example": "Zahlen Sie bar oder mit Karte?"},
            {"de": "gleich da drüben", "it": "proprio lì", "example": "Die Kasse ist gleich da drüben."},
            {"de": "ausverkauft", "it": "esaurito", "example": "Der Zopf ist leider ausverkauft."},
            {"de": "Das macht…", "it": "Fa (in totale)…", "example": "Das macht zusammen zwölf Franken."},
            {"de": "Kann ich Ihnen helfen?", "it": "Posso aiutarla?", "example": "Guten Tag, kann ich Ihnen helfen?"},
            {"de": "Sonst noch etwas?", "it": "Desidera altro?", "example": "Sonst noch etwas? Das ist alles, danke."},
        ],
        "swiss_variants": [
            {"standard": "Guten Tag!", "swiss": "Grüezi!", "it": "Buongiorno (saluto svizzero)"},
            {"standard": "Auf Wiedersehen.", "swiss": "Uf Wiederluege.", "it": "Arrivederci."},
            {"standard": "eine Tüte", "swiss": "es Säckli", "it": "un sacchetto"},
            {"standard": "zwanzig Franken", "swiss": "zwänzg Stutz", "it": "venti franchi (colloquiale)"},
        ],
        "imprevisti": [
            "Der Zopf ist ausverkauft.",
            "Die Kasse akzeptiert nur Barzahlung.",
            "Der Kunde findet die Eier nicht.",
            "Ein Produkt ist falsch ausgezeichnet.",
            "Die Tüte reißt beim Einpacken.",
        ],
        "goals": [
            "Nach einem Produkt fragen und es finden.",
            "Nach dem Preis fragen.",
            "Bar oder mit Karte bezahlen und die Quittung erhalten.",
            "Auf einen ausverkauften Artikel reagieren und eine Alternative wählen.",
        ],
    },
    {
        "slug": "zuhause-und-nachbarn",
        "title_de": "Zuhause und Nachbarn",
        "title_it": "Casa e vicini",
        "week_number": 2,
        "description": "Parlare con i vicini e descrivere la propria casa.",
        "role_label": "Nachbarin",
        "key_phrases": [
            {"de": "Grüezi, ich bin die neue Nachbarin.", "it": "Salve, sono la nuova vicina.", "example": "Grüezi, ich bin die neue Nachbarin, ich wohne oben."},
            {"de": "Sorry, war das zu laut gestern?", "it": "Scusa, ieri facevamo troppo rumore?", "example": "Sorry, war das zu laut gestern? Wir hatten Gäste."},
            {"de": "Haben Sie kurz Zeit?", "it": "Ha un attimo?", "example": "Haben Sie kurz Zeit? Ich muss etwas fragen."},
            {"de": "Können Sie mir helfen?", "it": "Può aiutarmi?", "example": "Können Sie mir helfen? Der Lift ist kaputt."},
            {"de": "Ich habe ein Paket für Sie angenommen.", "it": "Ho ritirato un pacco per lei.", "example": "Ich habe ein Paket für Sie angenommen, es ist bei mir."},
            {"de": "Wo ist der Kehrichtsack?", "it": "Dov'è il sacco dei rifiuti?", "example": "Wo ist der Kehrichtsack? Ich finde ihn nicht."},
            {"de": "Die Waschmaschine ist besetzt.", "it": "La lavatrice è occupata.", "example": "Die Waschmaschine ist besetzt, können wir tauschen?"},
            {"de": "Ab 22 Uhr ist Nachtruhe.", "it": "Dalle 22 c'è il riposo notturno.", "example": "Ab 22 Uhr ist Nachtruhe, bitte nicht so laut."},
            {"de": "Ich wohne im zweiten Stock.", "it": "Abito al secondo piano.", "example": "Ich wohne im zweiten Stock, direkt über Ihnen."},
            {"de": "Danke, das ist sehr nett.", "it": "Grazie, molto gentile.", "example": "Danke, das ist sehr nett von Ihnen."},
        ],
        "swiss_variants": [
            {"standard": "Guten Abend!", "swiss": "Gueten Obe!", "it": "Buonasera (svizzero)"},
            {"standard": "ein Abfallsack", "swiss": "es Kehrichtsäckli", "it": "un sacco dei rifiuti"},
            {"standard": "die Waschküche", "swiss": "d'Waschchuchi", "it": "la lavanderia (svizzero)"},
        ],
        "imprevisti": [
            "Die Waschmaschine ist besetzt, obwohl Sie laut Waschplan eingetragen sind.",
            "Der Kehrichtsack wurde falsch sortiert und nicht abgeholt.",
            "Die Nachbarn feiern eine Party nach 22 Uhr.",
            "Ein Paket wurde beim Nachbarn abgegeben, nicht bei Ihnen.",
            "Ein Velo steht im Treppenhaus und blockiert den Weg.",
        ],
        "goals": [
            "Sich beim Nachbarn vorstellen und begrüssen.",
            "Die eigene Wohnung beschreiben und etwas über das Haus fragen.",
            "Ein Problem (Lärm, Waschmaschine, Paket) ansprechen und eine Lösung finden.",
            "Sich bedanken und etwas vereinbaren (z. B. einen Termin oder einen Gefallen).",
        ],
    },
    {
        "slug": "schule-elternabend-und-lehrpersonen",
        "title_de": "Schule: Elternabend und Lehrpersonen",
        "title_it": "Scuola: colloquio e insegnanti",
        "week_number": 3,
        "description": "Partecipare a un colloquio genitori-insegnanti e parlare con gli insegnanti.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "wochenende-mit-freunden",
        "title_de": "Wochenende mit Freunden",
        "title_it": "Weekend con gli amici",
        "week_number": 4,
        "description": "Organizzare il weekend e fare progetti con gli amici.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "beim-arzt-und-in-der-apotheke",
        "title_de": "Beim Arzt und in der Apotheke",
        "title_it": "Dal medico e in farmacia",
        "week_number": 5,
        "description": "Descrivere i sintomi e comprare medicine in farmacia.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "buero-und-small-talk",
        "title_de": "Büro und Small Talk",
        "title_it": "Ufficio e small talk",
        "week_number": 6,
        "description": "Conversazioni brevi e di cortesia in ufficio.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "oeffentlicher-verkehr-und-sbb",
        "title_de": "Öffentlicher Verkehr und SBB",
        "title_it": "Trasporti pubblici e SBB",
        "week_number": 7,
        "description": "Biglietti, orari e coincidenze su treni e mezzi pubblici.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "feste-einladungen-geschenke",
        "title_de": "Feste, Einladungen, Geschenke",
        "title_it": "Feste, inviti, regali",
        "week_number": 8,
        "description": "Organizzare feste, invitare e fare regali.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "im-restaurant",
        "title_de": "Im Restaurant",
        "title_it": "Al ristorante",
        "week_number": 9,
        "description": "Ordinare, chiedere il conto e gestire piccoli problemi a tavola.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "probleme-reklamation-reparatur-hausverwaltung",
        "title_de": "Probleme: Reklamation, Reparatur, Hausverwaltung",
        "title_it": "Problemi: reclami, riparazioni, amministrazione",
        "week_number": 10,
        "description": "Reclamare, chiedere riparazioni e parlare con l'amministratore.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "meinungen-und-erzaehlen",
        "title_de": "Meinungen und Erzählen",
        "title_it": "Opinioni e racconti",
        "week_number": 11,
        "description": "Esprimere opinioni e raccontare esperienze.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
    {
        "slug": "wiederholung",
        "title_de": "Wiederholung",
        "title_it": "Ripasso",
        "week_number": 12,
        "description": "Ripasso generale degli scenari delle settimane precedenti.",
        "role_label": None,
        "key_phrases": [],
        "swiss_variants": [],
        "imprevisti": [],
        "goals": [],
    },
]


VOCAB = [
    # --- 20 parole della lezione pilota (obbligatorie) ---
    {"scenario_slug": "im-supermarkt", "de": "der Einkaufswagen", "it": "il carrello", "gender": "der", "plural": "die Einkaufswagen", "separable": False, "example_de": "Ich hole einen Einkaufswagen am Eingang."},
    {"scenario_slug": "im-supermarkt", "de": "die Kasse", "it": "la cassa", "gender": "die", "plural": "die Kassen", "separable": False, "example_de": "Die Kasse ist gleich da drüben."},
    {"scenario_slug": "im-supermarkt", "de": "das Regal", "it": "lo scaffale", "gender": "das", "plural": "die Regale", "separable": False, "example_de": "Die Äpfel stehen im Regal."},
    {"scenario_slug": "im-supermarkt", "de": "abwiegen", "it": "pesare (separabile)", "gender": None, "plural": None, "separable": True, "example_de": "Ich wiege die Äpfel ab."},
    {"scenario_slug": "im-supermarkt", "de": "im Angebot", "it": "in offerta", "gender": None, "plural": None, "separable": False, "example_de": "Die Äpfel sind diese Woche im Angebot."},
    {"scenario_slug": "im-supermarkt", "de": "die Quittung", "it": "lo scontrino", "gender": "die", "plural": "die Quittungen", "separable": False, "example_de": "Kann ich bitte die Quittung haben?"},
    {"scenario_slug": "im-supermarkt", "de": "ausverkauft", "it": "esaurito", "gender": None, "plural": None, "separable": False, "example_de": "Der Zopf ist leider ausverkauft."},
    {"scenario_slug": "im-supermarkt", "de": "Hätten Sie…?", "it": "Avrebbe…?", "gender": None, "plural": None, "separable": False, "example_de": "Hätten Sie noch frische Äpfel?"},
    {"scenario_slug": "im-supermarkt", "de": "sechs Eier", "it": "sei uova", "gender": None, "plural": None, "separable": False, "example_de": "Ich hätte gern sechs Eier."},
    {"scenario_slug": "im-supermarkt", "de": "brauchen", "it": "avere bisogno", "gender": None, "plural": None, "separable": False, "example_de": "Brauchen Sie eine Tüte?"},
    {"scenario_slug": "im-supermarkt", "de": "das Frühstück", "it": "la colazione", "gender": "das", "plural": None, "separable": False, "example_de": "Zum Frühstück esse ich einen Zopf."},
    {"scenario_slug": "im-supermarkt", "de": "der Zopf", "it": "la treccia di pane", "gender": "der", "plural": "die Zöpfe", "separable": False, "example_de": "Der Zopf ist heute ausverkauft."},
    {"scenario_slug": "im-supermarkt", "de": "die Mischung", "it": "il misto", "gender": "die", "plural": "die Mischungen", "separable": False, "example_de": "Ich nehme die Mischung aus Äpfeln und Birnen."},
    {"scenario_slug": "im-supermarkt", "de": "einpacken", "it": "imballare (separabile)", "gender": None, "plural": None, "separable": True, "example_de": "Können Sie das bitte einpacken?"},
    {"scenario_slug": "im-supermarkt", "de": "sammeln", "it": "raccogliere", "gender": None, "plural": None, "separable": False, "example_de": "Ich sammle Punkte mit der Kundenkarte."},
    {"scenario_slug": "im-supermarkt", "de": "das Bargeld / bar", "it": "i contanti / in contanti", "gender": "das", "plural": None, "separable": False, "example_de": "Ich zahle bar."},
    {"scenario_slug": "im-supermarkt", "de": "zurück", "it": "indietro / il resto", "gender": None, "plural": None, "separable": False, "example_de": "Hier ist Ihr Restgeld zurück."},
    {"scenario_slug": "im-supermarkt", "de": "gleich da drüben", "it": "proprio lì", "gender": None, "plural": None, "separable": False, "example_de": "Das Brot ist gleich da drüben."},
    {"scenario_slug": "im-supermarkt", "de": "das Bier", "it": "la birra", "gender": "das", "plural": "die Biere", "separable": False, "example_de": "Ich nehme noch ein Bier mit."},
    {"scenario_slug": "im-supermarkt", "de": "die Äpfel", "it": "le mele", "gender": None, "plural": "die Äpfel", "separable": False, "example_de": "Die Äpfel sind frisch."},
    # --- ulteriori parole curate dello scenario ---
    {"scenario_slug": "im-supermarkt", "de": "Ich hätte gern…", "it": "Vorrei…", "gender": None, "plural": None, "separable": False, "example_de": "Ich hätte gern ein Baguette."},
    {"scenario_slug": "im-supermarkt", "de": "die Tüte", "it": "il sacchetto", "gender": "die", "plural": "die Tüten", "separable": False, "example_de": "Brauchen Sie eine Tüte?"},
    {"scenario_slug": "im-supermarkt", "de": "zahlen", "it": "pagare", "gender": None, "plural": None, "separable": False, "example_de": "Zahlen Sie bar oder mit Karte?"},
    {"scenario_slug": "im-supermarkt", "de": "die Banane", "it": "la banana", "gender": "die", "plural": "die Bananen", "separable": False, "example_de": "Die Bananen sind sehr reif."},
    {"scenario_slug": "im-supermarkt", "de": "das Baguette", "it": "la baguette", "gender": "das", "plural": "die Baguettes", "separable": False, "example_de": "Wir haben frisches Baguette."},
    {"scenario_slug": "im-supermarkt", "de": "das Brot", "it": "il pane", "gender": "das", "plural": "die Brote", "separable": False, "example_de": "Ich brauche noch Brot."},
    {"scenario_slug": "im-supermarkt", "de": "frisch", "it": "fresco", "gender": None, "plural": None, "separable": False, "example_de": "Das Brot ist heute frisch."},
    {"scenario_slug": "im-supermarkt", "de": "der Franken", "it": "il franco", "gender": "der", "plural": "die Franken", "separable": False, "example_de": "Das macht zwölf Franken."},
    {"scenario_slug": "im-supermarkt", "de": "mit Karte", "it": "con carta", "gender": None, "plural": None, "separable": False, "example_de": "Kann ich mit Karte zahlen?"},
    {"scenario_slug": "im-supermarkt", "de": "kaufen", "it": "comprare", "gender": None, "plural": None, "separable": False, "example_de": "Ich möchte Obst kaufen."},
    {"scenario_slug": "im-supermarkt", "de": "die Milch", "it": "il latte", "gender": "die", "plural": None, "separable": False, "example_de": "Ich brauche eine Flasche Milch."},
    {"scenario_slug": "im-supermarkt", "de": "die Butter", "it": "il burro", "gender": "die", "plural": None, "separable": False, "example_de": "Die Butter ist im Kühlregal."},
    {"scenario_slug": "im-supermarkt", "de": "der Käse", "it": "il formaggio", "gender": "der", "plural": None, "separable": False, "example_de": "Welchen Käse empfehlen Sie?"},
    {"scenario_slug": "im-supermarkt", "de": "das Gemüse", "it": "la verdura", "gender": "das", "plural": None, "separable": False, "example_de": "Das Gemüse ist heute sehr frisch."},
    {"scenario_slug": "im-supermarkt", "de": "das Obst", "it": "la frutta", "gender": "das", "plural": None, "separable": False, "example_de": "Wo finde ich das Obst?"},
    {"scenario_slug": "im-supermarkt", "de": "die Flasche", "it": "la bottiglia", "gender": "die", "plural": "die Flaschen", "separable": False, "example_de": "Ich nehme zwei Flaschen Wasser."},
    {"scenario_slug": "im-supermarkt", "de": "das Wasser", "it": "l'acqua", "gender": "das", "plural": None, "separable": False, "example_de": "Ich brauche Mineralwasser."},
    {"scenario_slug": "im-supermarkt", "de": "der Saft", "it": "il succo", "gender": "der", "plural": "die Säfte", "separable": False, "example_de": "Haben Sie Apfelsaft?"},
    {"scenario_slug": "im-supermarkt", "de": "der Preis", "it": "il prezzo", "gender": "der", "plural": "die Preise", "separable": False, "example_de": "Der Preis steht am Regal."},
    {"scenario_slug": "im-supermarkt", "de": "das Sonderangebot", "it": "l'offerta speciale", "gender": "das", "plural": "die Sonderangebote", "separable": False, "example_de": "Dieses Bier ist im Sonderangebot."},
    # --- Scenario 2 "Zuhause und Nachbarn" (curato, 40 vocab) ---
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Nachbar", "it": "il vicino", "gender": "der", "plural": "die Nachbarn", "separable": False, "example_de": "Der Nachbar ist sehr freundlich."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Nachbarin", "it": "la vicina", "gender": "die", "plural": "die Nachbarinnen", "separable": False, "example_de": "Die Nachbarin hat mir geholfen."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Wohnung", "it": "l'appartamento", "gender": "die", "plural": "die Wohnungen", "separable": False, "example_de": "Meine Wohnung liegt im zweiten Stock."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "das Haus", "it": "la casa", "gender": "das", "plural": "die Häuser", "separable": False, "example_de": "Das Haus hat einen kleinen Garten."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Stock", "it": "il piano", "gender": "der", "plural": "die Stockwerke", "separable": False, "example_de": "Wir wohnen im zweiten Stock."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "das Treppenhaus", "it": "la tromba delle scale", "gender": "das", "plural": "die Treppenhäuser", "separable": False, "example_de": "Im Treppenhaus steht ein Velo."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Lift", "it": "l'ascensore", "gender": "der", "plural": "die Lifte", "separable": False, "example_de": "Der Lift ist heute kaputt."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Briefkasten", "it": "la cassetta delle lettere", "gender": "der", "plural": "die Briefkästen", "separable": False, "example_de": "Dein Paket ist im Briefkasten."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Keller", "it": "la cantina", "gender": "der", "plural": "die Keller", "separable": False, "example_de": "Die Waschmaschine steht im Keller."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Waschküche", "it": "la lavanderia", "gender": "die", "plural": "die Waschküchen", "separable": False, "example_de": "Die Waschküche ist im Keller."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Waschmaschine", "it": "la lavatrice", "gender": "die", "plural": "die Waschmaschinen", "separable": False, "example_de": "Die Waschmaschine ist besetzt."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Waschplan", "it": "il piano della lavanderia", "gender": "der", "plural": "die Waschpläne", "separable": False, "example_de": "Heute bin ich laut Waschplan dran."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Kehricht", "it": "i rifiuti", "gender": "der", "plural": None, "separable": False, "example_de": "Der Kehricht wird am Dienstag abgeholt."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Kehrichtsack", "it": "il sacco dei rifiuti", "gender": "der", "plural": "die Kehrichtsäcke", "separable": False, "example_de": "Der Kehrichtsack ist voll."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Hausverwaltung", "it": "l'amministrazione dello stabile", "gender": "die", "plural": "die Hausverwaltungen", "separable": False, "example_de": "Ich rufe die Hausverwaltung an."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Miete", "it": "l'affitto", "gender": "die", "plural": "die Mieten", "separable": False, "example_de": "Die Miete ist 1800 Franken."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Nachtruhe", "it": "il riposo notturno", "gender": "die", "plural": None, "separable": False, "example_de": "Ab 22 Uhr ist Nachtruhe."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Lärm", "it": "il rumore", "gender": "der", "plural": None, "separable": False, "example_de": "Der Lärm kommt von oben."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "das Velo", "it": "la bicicletta", "gender": "das", "plural": "die Velos", "separable": False, "example_de": "Mein Velo steht im Keller."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "die Tür", "it": "la porta", "gender": "die", "plural": "die Türen", "separable": False, "example_de": "Die Tür ist offen."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "der Schlüssel", "it": "la chiave", "gender": "der", "plural": "die Schlüssel", "separable": False, "example_de": "Ich habe den Schlüssel verloren."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "das Säckli", "it": "il sacchetto", "gender": "das", "plural": "die Säckli", "separable": False, "example_de": "Ich brauche ein Säckli."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "das Paket", "it": "il pacco", "gender": "das", "plural": "die Pakete", "separable": False, "example_de": "Das Paket ist bei der Nachbarin."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "klingeln", "it": "suonare (il campanello)", "gender": None, "plural": None, "separable": False, "example_de": "Ich klingle bei der Nachbarin."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "läuten", "it": "suonare", "gender": None, "plural": None, "separable": False, "example_de": "Es läutet an der Tür."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "klopfen", "it": "bussare", "gender": None, "plural": None, "separable": False, "example_de": "Er klopft an die Tür."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "wohnen", "it": "abitare", "gender": None, "plural": None, "separable": False, "example_de": "Ich wohne in Zürich."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "einziehen", "it": "trasferirsi (entrare)", "gender": None, "plural": None, "separable": True, "example_de": "Wir ziehen nächste Woche ein."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "ausziehen", "it": "trasferirsi (uscire)", "gender": None, "plural": None, "separable": True, "example_de": "Sie zieht bald aus."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "umziehen", "it": "traslocare", "gender": None, "plural": None, "separable": True, "example_de": "Wir ziehen in eine neue Wohnung um."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "helfen", "it": "aiutare", "gender": None, "plural": None, "separable": False, "example_de": "Kannst du mir helfen?"},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "sich beschweren", "it": "lamentarsi", "gender": None, "plural": None, "separable": False, "example_de": "Er beschwert sich über den Lärm."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "besprechen", "it": "discutere", "gender": None, "plural": None, "separable": False, "example_de": "Wir müssen das Problem besprechen."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "vereinbaren", "it": "concordare", "gender": None, "plural": None, "separable": False, "example_de": "Wir vereinbaren einen Termin."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "putzen", "it": "pulire", "gender": None, "plural": None, "separable": False, "example_de": "Ich putze am Samstag."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "reparieren", "it": "riparare", "gender": None, "plural": None, "separable": False, "example_de": "Kannst du den Wasserhahn reparieren?"},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "leise", "it": "a bassa voce", "gender": None, "plural": None, "separable": False, "example_de": "Bitte sei nachts leise."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "laut", "it": "rumoroso", "gender": None, "plural": None, "separable": False, "example_de": "Die Musik ist zu laut."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "besetzt", "it": "occupato", "gender": None, "plural": None, "separable": False, "example_de": "Die Waschmaschine ist besetzt."},
    {"scenario_slug": "zuhause-und-nachbarn", "de": "nebenan", "it": "di fianco / accanto", "gender": None, "plural": None, "separable": False, "example_de": "Die Nachbarin wohnt nebenan."},
]
